# Generated by Django 4.2.1 on 2023-11-06 10:47

import django.core.validators
from django.db import migrations, models
import django.utils.timezone
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_image_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='full_image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='images/fullHD'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='image',
            name='img',
            field=easy_thumbnails.fields.ThumbnailerImageField(upload_to='images/images', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('png', 'jpg', 'jpeg', 'gif', 'ico'))]),
        ),
    ]
