# Generated by Django 4.2.1 on 2023-11-06 10:49

import django.core.validators
from django.db import migrations, models
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_image_full_image_alter_image_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='full_image',
            field=models.ImageField(upload_to='images'),
        ),
        migrations.AlterField(
            model_name='image',
            name='img',
            field=easy_thumbnails.fields.ThumbnailerImageField(upload_to='images', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('png', 'jpg', 'jpeg', 'gif', 'ico'))]),
        ),
    ]
